-- AlterTable
ALTER TABLE `Data` MODIFY `ppm` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `co_ppm` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `co2_ppm` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `alkol_ppm` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `aseton_ppm` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `temperature` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `humidity` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `heat_index` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `pressure` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `altitude` DOUBLE NOT NULL DEFAULT 0;
